#!/bin/bash
# /etc/init.d/autodoor
 
### BEGIN INIT INFO
 
case "$1" in
    start)
        echo "Starting autodoor"
        /var/www/key.py &
        ;;
    stop)
        echo "Stopping autodoor"
        #killall key.py
        kill $(ps aux | grep -m 1 'python3 /var/www/key.py' | awk '{ print $2 }')
        ;;
    *)
        echo "Usage: service autodoor start|stop"
        exit 1
        ;;
esac
exit 0
